WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 256
VIRTUAL_HEIGHT = 144 

BUTTON_SIZE = 16

CALCULATOR_WIDTH = 80
CALCULATOR_HEIGHT = 120

-- calculator position: 88, 12
CALCULATOR_X = (VIRTUAL_WIDTH - CALCULATOR_WIDTH) / 2
CALCULATOR_Y = (VIRTUAL_HEIGHT - CALCULATOR_HEIGHT) / 2

CALSCREEN_WIDTH = 70
CALSCREEN_HEIGHT = 20

-- 93, 17
CALSCREEN_X = (CALCULATOR_WIDTH - CALSCREEN_WIDTH) / 2 + CALCULATOR_X
CALSCREEN_Y = CALCULATOR_Y + 5
